[package]
name = "my_parser_kma_group_8"
version = "0.1.1"
edition = "2021"
license = "MIT"
description = "A brief description of my crate"
exclude = ["target/*", "*.md", "*.lock", "examples/*", ".git/*"]

[dependencies]
peg = "0.8.4"